# Generated by Django 4.1.6 on 2023-02-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idbodega', models.IntegerField()),
                ('nombrebodega', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproducto', models.IntegerField()),
                ('nombreproducto', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('existencias', models.IntegerField()),
                ('idbodega', models.IntegerField()),
                ('idproveedor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproveedor', models.CharField(max_length=30)),
                ('empresa', models.CharField(max_length=30)),
                ('actividad', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
    ]
